### PR TITLE
Provides administrator the ability to combine quarantine reports into a single report

### LINKED ISSUE #608: Problem with Quarantine report and user/domain
Hello!

Something wrong with quarantine report.

USER user1@domain1.tld receive all message for domain1.tld

ADMIN DOMAIN user@domain.tld receive all domain1.tld but not message for domain.tld (domain1.tld is in filter for domain.tld)

Could you verify on your side?

### PR DESCRIPTION
**Pull request by asuweb**
Fixes #608 

Allows administrators to combine quarantine_reports into a single report containing all of the users filters.

Fixes a bug in the case of a single report per filter, where previously each filter report received quarantine mail for the parent user as well.

### CODE REVIEW

File: tools/Cron_jobs/mailwatch_quarantine_report.php [hunk 1]
```diff
@@ -345,6 +345,7 @@
                         foreach ($quarantine_list as $item) {
                             $list .= $item . ', ';
                         }
+                        $list = substr($list,0,-2);
```
Comment (asuweb) [inline tools/Cron_jobs/mailwatch_quarantine_report.php]: Yes, I'm not sure why I didn't use that the first time! Doh!
