### PR TITLE
Quote handling in mailwatch_milter_relay.php

### LINKED ISSUE #1170: Single quote handling in message ID
### Issue summary
Single quotes need handled properly in the message ID field.

### Steps to reproduce
1. Send an email with a single quote in the message ID

### Expected result
Quote should be escaped before inserting into DB.

### Actual result
https://forum.efa-project.org/viewtopic.php?f=5&t=4220&p=15708

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1170

### CODE REVIEW

File: tools/Postfix_relay/mailwatch_milter_relay.php [hunk 1]
```diff
@@ -50,7 +50,7 @@ function doit($input)
     while ($line = fgets($fp, 2096)) {
         if (preg_match('/^.*postfix\/cleanup.*: (\S+): message-id=(\S+)$/', $line, $explode)) {
             $smtp_id = $explode[1];
-            $message_id = $explode[2];
+            $message_id = preg_replace("'", "''", $explode[2]);
```
Comment (endelwar) [inline tools/Postfix_relay/mailwatch_milter_relay.php]: I think that a `safe_value()` on both $smtp_id and $message_id must be used, because these 2 values are used in SQL query as is, and are prone to sql inject attack

Comment (endelwar) [reply tools/Postfix_relay/mailwatch_milter_relay.php]:
```php
$smtp_id = safe_value($explode[1]);
$message_id = safe_value($explode[2]);
```

Comment (ghost) [reply tools/Postfix_relay/mailwatch_milter_relay.php]: That makes more sense.
