### PR TITLE
Handle latin encoded chars found in reports and messageid

### LINKED ISSUE #1198: Not logging mail to SQL
### Issue summary
Hi,

I have a fresh install on centos 8.2.2004 with this versions:
image

I have installed the package required:
perl-DBD-MySQL-4.046-3.module_el8.1.0+203+e45423dc.x86_64
perl-DBI-1.641-3.module_el8.1.0+199+8f0a6bbd.x86_64
image
image
image
image

### Steps to reproduce
I have start mailscanner with this command: MailScanner --debug and return this error:
`[root@mail ~]# MailScanner --debug

In Debugging mode, not forking...
Trying to setlogsock(unix)
internal error, python traceback seen in response
Building a message batch to scan...
Have a batch of 4 messages.
internal error, python traceback seen in response
internal error, python traceback seen in response
internal error, python traceback seen in response
internal error, python traceback seen in response
Stopping now as you are debugging me.
Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xE3o spa...' for column `mailscanner`.`maillog`.`spamreport` at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 226, <CLIENT> line 30.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 1053.
`
### Actual result
I have verify and database on utf8mb4_unicode_ci
I have search but unsuccesfully resolve my problem. 

Can you help me on this problem?
Thank you

### Version and method
 - MailWatch Version: 1.2.15
 - Install type: zip
 - Updated from an older MailWatch or fresh install: Fresh install 

### Server configuration
 - Operation System: CentOS
 - PHP version: 7.2.24
 - Database: MariaDB 
 - Mail Server: Postfix
 - Used web server: Apache

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Fixes #1198

File: MailScanner_perl_scripts/MailWatch.pm [hunk 1]
```diff
@@ -384,26 +384,26 @@ sub MailWatchLogging {
...
+    $msg{reports} = fix_latin($reports);
     $msg{hostname} = $hostname;
     $msg{date} = $date;
     $msg{"time"} = $time;
     $msg{headers} = join("\n", map { fix_latin($_)} @{$message->{headers}});
     $msg{quarantined} = $quarantined;
     $msg{rblspamreport} = $message->{rblspamreport};
     $msg{token} = $token;
-    $msg{messageid} = $messageid;
+    $msg{messageid} = fix_latin($messageid);
```
Comment (endelwar) [inline MailScanner_perl_scripts/MailWatch.pm:406]: Isn't `messageid` limited to ASCII charset?

Comment (ghost) [reply MailScanner_perl_scripts/MailWatch.pm:406]: A non-compliant message seems it can have latin chars in here so it bombs out.
