### PR TITLE
send empty quarantine reports over user_manager; fixes 1054

### LINKED ISSUE #1054: Error during "Send Daily Report" if no email address
### Issue summary
Got error we click on "Send Daily Report" without email address in "Quarantine Report Recipient".

### Steps to reproduce
1. click on "Send Now"

sc

### Actual result

> Warning: array_merge() expects at least 1 parameter, 0 given in /var/www/html/mailscanner/quarantine_report.inc.php on line 392
> The quarantine report was successfully sent.

If "Quarantine Report Recipient" is empty, we should have an alert message as "Please enter an email address in Quarantine Report Recipient first".

### Version and method
 - MailWatch Version: 2.2.8

### Server configuration
 - Operation System: Debian Jessie uptodate
 - PHP version: 5.6.33
 - Database: MariaDB 10.1
 - Mail Server: Exim
 - Used web server: Apache

### Client configuration 
 - Operation System: OSX 10.13
 - Browser: Safari 11.1 or others

### PR DESCRIPTION
**Pull request by Skywalker-11**
Problem exists if there are no quarantined mails for the user (currently generates an php error)

This PR adds checks to prevent that error and enables sending of empty reports over user_manager.
fixes #1054

### CODE REVIEW

File: mailscanner/languages/en.php [hunk 1]
```diff
@@ -934,6 +934,7 @@
     'message61' => 'The variable %s is empty, please set a value in conf.php.',
     'text611' => 'Quarantine Report for %s',
     'text612' => 'In the last %s day(s) you have received %s e-mails that have been quarantined and are listed below. All messages in the quarantine are automatically deleted %s days after the date that they were received.',
+    'text613' => 'In the last %s day(s) you have received no e-mails that have been quarantined.',
```
Comment (stefaweb) [inline mailscanner/languages/en.php:937]: For fr.php

'text613' => 'Durant le(s) %s dernier(s) jour(s) vous avez reçu %s messages qui ont été mis en Quarantaine.',

Comment (Skywalker-11) [reply mailscanner/languages/en.php:937]: done
